In [ ]:
*******UNIQUE AND SET LOGIC******
ARRAY SET OPERATIONS

In [6]:
import numpy as np
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
players=np.array(["Bob","Mary","Jahn","Will"])

In [3]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [7]:
np.unique(players)

array(['Bob', 'Jahn', 'Mary', 'Will'], dtype='<U4')

In [8]:
np.intersect1d(names, players)

array(['Bob', 'Will'], dtype='<U4')

In [9]:
np.union1d(names, players)
#union1d(x, y) Compute the sorted union of elements

array(['Bob', 'Jahn', 'Joe', 'Mary', 'Will'], dtype='<U4')

In [10]:
np.in1d(names, players)
#in1d(x, y) Compute a Boolean array indicating whether each element of x is contained in y

array([ True,  True, False,  True,  True, False, False])

In [11]:
np.setdiff1d(names, players)
#setdiff1d(x, y) Set difference, elements in x that are not in y

array(['Joe'], dtype='<U4')

In [13]:
np.setxor1d(names, players)
#setxor1d(x, y) Set symmetric differences; elements that are in either of the arrays, but not both

array(['Jahn', 'Joe', 'Mary'], dtype='<U4')

In [ ]:
******** LINEAR ALGEBRA *********

In [14]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [15]:
x @ np.ones(3)

array([ 6., 15.])

In [20]:
x=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9,]])
y=np.array([[11, 12, 13],[14, 15, 16],[17, 18, 19]])

In [25]:
np.diag(x)

array([1, 5, 9])

In [23]:
np.dot(x, y)

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [24]:
np.trace(x)

15