In [1]:
import numpy as np
a=np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
a[:2,1:] #row wise slicing except the first index

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [7]:
a[:2,:2] #column-wise slicing starting from zeroth index and stop at 2 index 

array([[0, 1],
       [5, 6]])

In [10]:
low_dim_slice=a[2,:1]
low_dim_slice

array([10])

In [19]:
import numpy as np
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
a.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [15]:
np.dot(a.T, a)


array([[45, 54, 63],
       [54, 66, 78],
       [63, 78, 93]])