In [ ]:
 ********** Mathematical and Statistical Methods ************

In [5]:
import numpy as np
rng = np.random.default_rng(seed=12345)
arr = rng.standard_normal((2, 3))
arr

array([[-1.42382504,  1.26372846, -0.87066174],
       [-0.25917323, -0.07534331, -0.74088465]])

In [6]:
np.mean(arr)

-0.3510265850525223

In [7]:
np.sum(arr)

-2.106159510315134

In [8]:
arr.sum()

-2.106159510315134

In [10]:
arr.mean(axis=0)

array([-0.84149914,  0.59419258, -0.8057732 ])

In [11]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [12]:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [14]:
arr.cumsum(axis=0) #cumulative sum is calculated column-wise

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [15]:
arr.cumsum(axis=1) #cumulative sum is calculated row-wise

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]])

In [17]:
import numpy as np
rng = np.random.default_rng(seed=12345)
arr = np.arange(2,10)
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.sum(arr)

44

In [20]:
np.mean(arr)

5.5

In [21]:
np.std(arr)

2.29128784747792

In [22]:
np.var(arr)

5.25

In [23]:
np.min(arr)

2

In [24]:
np.max(arr)

9

In [25]:
np.argmin(arr)
#argmin, argmax Indices of minimum and maximum elements, respectively

0

In [26]:
np.argmax(arr)

7

In [27]:
np.cumsum(arr) 
#cumsum Cumulative sum of elements starting from 0

array([ 2,  5,  9, 14, 20, 27, 35, 44])

In [28]:
np.cumprod(arr)
#cumprod Cumulative product of elements starting from 1

array([     2,      6,     24,    120,    720,   5040,  40320, 362880])

In [46]:
arr = rng.standard_normal(6)
arr

array([-0.4587934 , -1.17576966,  0.0750525 , -0.40899022,  1.75653198,
        0.86092307])

In [47]:
(arr <= 0 ).sum() #non-negative

3

In [48]:
(arr > 0 ).sum() #positive

3

In [49]:
arr.sort()
arr

array([-1.17576966, -0.4587934 , -0.40899022,  0.0750525 ,  0.86092307,
        1.75653198])