In [1]:
a=10
a

10

In [2]:
import numpy as np
a=np.array([1,2,3])
b=np.int8(a)
b

array([1, 2, 3], dtype=int8)

In [3]:
import numpy as np
a=np.array([1,2,3])
b=np.uint8(a)
b

array([1, 2, 3], dtype=uint8)

In [14]:
import numpy as np
a=np.array([1,2,3])
print(a.dtype)

int32


In [15]:
import numpy as np
a=np.array([1,2.9,3])
print(a.dtype)

float64


In [16]:
import numpy as np
a=np.array([1,2+9j,3])
print(a.dtype)

complex128


In [17]:
import numpy as np
a=np.array([1,2,3])
b=np.int16(a)
b

array([1, 2, 3], dtype=int16)

In [5]:
import numpy as np
a=np.array([1,2,3])
b=np.float32(a)
b

array([1., 2., 3.], dtype=float32)

In [10]:
import numpy as np
a=np.array([1,2,3])
b=np.complex64(a)
b

array([1.+0.j, 2.+0.j, 3.+0.j], dtype=complex64)