In [2]:
import numpy as np
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
b=np.array([[1,2,3],[5,6,7]])
b

array([[1, 2, 3],
       [5, 6, 7]])

In [4]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [5]:
a*10

array([10, 20, 30, 40])

In [6]:
a+2

array([3, 4, 5, 6])

In [7]:
a.shape

(4,)

In [8]:
b.shape

(2, 3)

In [9]:
c.shape

(1, 3, 3)

In [10]:
import numpy as np
ab=np.arange(10)
ab

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
ab=np.arange(1,20,2)
ab

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [26]:
import numpy as np
a=np.array([1,2,4,5,6])
a
b=np.array(a)
b

array([1, 2, 4, 5, 6])

In [27]:
a.ndim

1

In [28]:
b.ndim

1

In [29]:
a.shape

(5,)

In [31]:
a.dtype

dtype('int32')

In [33]:
a=np.zeros([2,3])
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
b=np.zeros_like([2,3])
b

array([0, 0])

In [34]:
b=np.empty([2,3])
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [36]:
a=np.empty((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
c=np.empty((2))
c

array([1.1583537e-311, 0.0000000e+000])

In [44]:
np.empty_like([2,3])

array([-267517576,  234954496])

In [46]:
np.asarray((10))

array(10)

In [47]:
np.asarray((2,3))
#asarray() This function is used to create an array by using the existingdata in the form of lists, or tuples

array([2, 3])

In [57]:
import numpy as np
a=([1,2,3],[4,5,6],[7,8,9]) #numpy.asarray()function is used when we want to convert input to an array. Input can be lists, lists of tuples, tuples, tuples of tuples, tuples of lists and arrays.
a
b=np.asarray(a,dtype=float,order='C')
#dtype : [data-type, optional] By default, the data-type is inferred from the input data.
#order : Whether to use row-major (C-style) or column-major (Fortran-style) memory representation. Defaults to ‘C’.
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [70]:
import numpy as np
a=np.ones([2,2,3],dtype=int,order='f') #syntax=ones(shape, dtype=None, order='C')
a 
#Notice that the elements are having the default data type as the float. That’s why the ones are 1. in the array.
#row-major format, using the keyword argument order='C' ,
#and the column-major format, using the keyword argument order='F' , when the array is created or reshaped. The default format is row-major.

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [68]:
import numpy as np
a=np.ones_like([2,3],dtype=complex)
a

array([1.+0.j, 1.+0.j])

In [73]:
import numpy as np
c=np.ones_like((2,3))
c

array([1, 1])

In [75]:
import numpy as np
a=np.arange(2,10).reshape(2,4).astype(float)
a

array([[2., 3., 4., 5.],
       [6., 7., 8., 9.]])

In [81]:
import numpy as np
b=np.arange(2,19,2,dtype=float).reshape(3,3)
b

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [88]:
import numpy as np
a=np.ones((2,3),dtype=float)
b=np.ones_like(a)
b
#We implement the numpy.ones_like() function on 'a' and assign the result to another variable called 'b'.

array([[1., 1., 1.],
       [1., 1., 1.]])

In [97]:
import numpy as np
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [93]:
import numpy as np
a=np.zeros((2,3),dtype=float)
b=np.zeros_like(a)
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [107]:
import numpy as np
a=np.eye(2,10,2)
a

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [106]:
b=np.identity(10)
b

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [109]:
import numpy as np
a=np.full((2,3),(1,2,3),dtype=float)
a
#numpy.full(shape, fill_value, dtype = None, order = ‘C’) :
    Return a new array with the same shape and type as a given array filled with a fill_value.

array([[1., 2., 3.],
       [1., 2., 3.]])

In [112]:
import numpy as np
a=np.full((3,3),(3,2,1),dtype=int)
a
b=np.full_like(a,(3,2,1))
b

array([[3, 2, 1],
       [3, 2, 1],
       [3, 2, 1]])

In [115]:
import numpy as np
a=np.arange(1,10,dtype=int).reshape(3,3)
b=np.full_like(a,(3,2,1))
b

array([[3, 2, 1],
       [3, 2, 1],
       [3, 2, 1]])