In [2]:
# A)WORKING WITH ARRAYS
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
b=[34,"hi",0,True]
c=np.array(b, dtype=bool)
c

array([ True,  True, False,  True])

In [6]:
c=np.array([1,2,3,4,5])
d=np.extract(c>2, c)
d

array([3, 4, 5])

In [8]:
c=np.array([1,2,3,4,5,6])
d=np.where(c>3,10,c)
d

array([ 1,  2,  3, 10, 10, 10])

In [9]:
c=np.array([1,2,3,4,5,6])
d=np.where(c>3,10,c)
print(c)
print(d)

[1 2 3 4 5 6]
[ 1  2  3 10 10 10]


In [12]:
a=np.arange(25)
b=a.reshape(5,5)
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [21]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
b=np.where((a>=5)&(a<=9))
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
(array([4, 5, 6, 7, 8], dtype=int64),)


In [22]:
#B]  Write a program to sort a list of tuples based on multiple keys using sorted. The list should be sorted first
# by the second element of each tuple in descending order,
list=[(3,'c'),(1,'a'),(2,'b'),(2,'a'),(1,'b'),(3,'a')]
sorted_list=sorted(list, key=lambda x:(-ord(x[1]),x[0]))
sorted_list

[(3, 'c'), (1, 'b'), (2, 'b'), (1, 'a'), (2, 'a'), (3, 'a')]

In [26]:
# B)MULTIPLE ARRAYS
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[6,7,8],[9,10,5]])
c=np.vstack((a,b))
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 9, 10,  5]])

In [27]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[6,7,8],[9,10,5]])
c=np.hstack((a,b))
c

array([[ 1,  2,  3,  6,  7,  8],
       [ 4,  5,  6,  9, 10,  5]])

In [30]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[7,8,9]])
c=np.intersect1d(a,b)
c


array([1, 2, 3])

In [31]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[7,8,9]])
c=np.setdiff1d(a,b)
c

array([4, 5, 6])

In [37]:
a=np.array([4,5,6,1,2,3,])
b=np.array([7,8,9,1,2,3,])
c=np.where(a==b)
c

(array([3, 4, 5], dtype=int64),)

In [42]:
# B] How do you access the first element of the first row of a 3D NumPy arrayimport numpy as np
a=np.arange(18)
a
b=a.reshape(3,2,3)
print("reshape array:")
print(b)
c=b[0,0,0]
print("first element of the first row:")
print(c)

reshape array:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]
first element of the first row:
0


In [7]:
# C] Write a program that reads a list of integers from the user and calculates their sum.
def calculate_sum():
    total = 0
    while True:
        user_input = input("enter an interger (or 'stop' to finish):")
        if user_input.lower()=='stop':
            break
        try:
            total+=int(user_input)
        except valueError:
            print("invalid error")
    return total
print("the sum is:", calculate_sum())

enter an interger (or 'stop' to finish): 2
enter an interger (or 'stop' to finish): 5
enter an interger (or 'stop' to finish): stop


the sum is: 7


In [8]:
# C] MULTI-DIMENSIONAL ARRAYS
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.reshape(a,(1, -1))
b

array([[1, 2, 3, 4, 5, 6]])

In [13]:
import numpy as np
a=np.arange(9).reshape(3,3)
print("array")
print(a)
col1=1
col2=2
a[:, [col1, col2]]=a[:, [col2, col1]]
print("array after swap the columns:")
print(a)

array
[[0 1 2]
 [3 4 5]
 [6 7 8]]
array after swap the columns:
[[0 2 1]
 [3 5 4]
 [6 8 7]]


In [15]:
# B) Write a program that uses a lambda function to filter a list of strings to contain only those that have length greater than 5
String = ["apple","banana","orange","mango","custord"]
filtered_strings = list(filter(lambda s: len(s)>5, String))
filtered_strings

['banana', 'orange', 'custord']

In [18]:
# 4] STATISTICAL ANALYSIS
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
mean=np.mean(a)
median=np.median(a)
std=np.std(a)
print("mean:",mean)
print("median:",median)
print("standard deviation:", std)

mean: 5.0
median: 5.0
standard deviation: 2.581988897471611


In [21]:
a=np.arange(101)
b=np.percentile(a, q=[25,50, 75])
b

array([25., 50., 75.])

In [25]:
a=np.array([1,2,3,4,5,6])
b=np.array([6,5,4,3,2,1])
c=np.linalg.norm((a-b))
c

8.366600265340756

In [31]:
a=np.random.randint(0,100,500)
b=a+np.random.randint(0,100,500)
c=np.corrcoef(a,b)
c

array([[1.       , 0.7088724],
       [0.7088724, 1.       ]])

In [32]:
pop=np.array(['a','b','c','d','e'])
prp=np.array([0.2,0.1,0.3,0.4,0.5])
prp=prp/prp.sum()
sample=np.random.choice(pop, size=3, p=prp)
print(sample)

['b' 'd' 'c']


In [33]:
a=np.random.randint(10, size=10)
movavg=np.convolve(a, np.ones(3)/3, mode='valid')
print(a)
print(movavg)

[4 4 8 7 7 4 4 9 6 4]
[5.33333333 6.33333333 7.33333333 6.         5.         5.66666667
 6.33333333 6.33333333]


In [35]:
# B]How do you access the elements of the second column of the second row and the third row of a 2D NumPy array? 
a=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
element_second_row_second_column=a[1,1]
element_third_row_second_column=a[2,1]
print(element_second_row_second_column)
print(element_third_row_second_column)

5
8


In [3]:
# C] Write a program to remove all stop words from a string using regular expressions. 
import re
def remove_stop_words(text, stop_words):
    pattern = r'\b(?:{})\b'.format('|'.join(stop_words))
    cleaned_text=re.sub(pattern, ' ', text, flags=re.IGNORECASE)
    return cleaned_text.strip()
text="This is a sample text with some common stop words such as the, is, and with."
stop_words=["the","is","and","with","a","such"]
cleaned_text=remove_stop_words(text, stop_words)
print("Cleaned text:",cleaned_text)

Cleaned text: This     sample text   some common stop words   as  ,  ,    .


In [4]:
# 5] DATA CLEANING
import numpy as np
a=np.array([[1,2,3],[4,5,np.nan]])
np.argwhere(np.isnan(a))

array([[1, 2]], dtype=int64)

In [7]:
a=np.array([[1,2,3],[4,5,np.nan]])
a[~np.isnan(a).any(axis=1),:]

array([[1., 2., 3.]])

In [9]:
a=np.array([[1,2,3],[4,5,np.nan]])
a[np.isnan(a)]=0
a

array([[1., 2., 3.],
       [4., 5., 0.]])

In [10]:
a=np.array([[1,2,3],[4,5,np.nan]])
a[~np.isnan(a)]

array([1., 2., 3., 4., 5.])

In [77]:
# C]How do you access the last element of the last row of the last block of a 3D NumPy array?
import numpy as np
array = np.arange(27).reshape(3, 3, 3)
last_row=array[-1, -1, -1]
print("original array")
print(array)
print("last row of the last block:")
print(last_row)

original array
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
last row of the last block:
26


In [21]:
# 6] DATA TRANSFORMATION
import numpy as np
a=np.array([1,2,3,4,5])
arr_normalized=(a-np.min(a))/(np.max(a)-np.min(a))
print("original array")
print(a)
print("\nNormalized array (between 0 and 1)")
print(arr_normalized)

original array
[1 2 3 4 5]

Normalized array (between 0 and 1)
[0.   0.25 0.5  0.75 1.  ]


In [17]:
import numpy as np
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
min_max = np.min(a, axis=1)/np.max(a, axis=1)
print(a)
print(min_max)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0.33333333 0.66666667 0.77777778]


In [18]:
#C] Write a dictionary comprehension that generates a dictionary where the keys are the first 10 even numbers   
even_numbers = range(2,21,2)
even_squares_dict = {num: num ** 2 for num in even_numbers}
print(even_squares_dict)

{2: 4, 4: 16, 6: 36, 8: 64, 10: 100, 12: 144, 14: 196, 16: 256, 18: 324, 20: 400}


In [5]:
# 7] PANDAS BASICS
pip install pandas

SyntaxError: invalid syntax (2664942803.py, line 2)

In [21]:
pip show pandas

Name: pandas
Version: 2.1.4
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: 
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License

Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
All rights reserved.

Copyright (c) 2011-2023, Open source contributors.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be u

In [19]:
import pandas as pd
print(pd._version_)


AttributeError: module 'pandas' has no attribute '_version_'

In [3]:
import pandas as pd
import numpy as np
list=[1,2,3,4,5,6]
series_from_list=pd.Series(list)
array=np.array([1,2,3,4,5,6])
series_from_array=pd.Series(array)
dict={'a':10,'b':20,'c':30}
series_from_dict=pd.Series(dict)
print("Series from list:",list)
print("Series from array:",array)
print("Series from dict:",dict)


Series from list: [1, 2, 3, 4, 5, 6]
Series from array: [1 2 3 4 5 6]
Series from dict: {'a': 10, 'b': 20, 'c': 30}


In [12]:
import pandas as pd
a=pd.Series([10,20,30],index=['a','b','c'],name='values')
b=a.reset_index()
b.columns=['index','values']
print("DataFrame with series index as a column")
print(b)

DataFrame with series index as a column
  index  values
0     a      10
1     b      20
2     c      30


In [78]:
import pandas as pd
x=pd.Series(["apple","banana","mango","kiwi","orange"],name='Fruits')
y=pd.Series(["red","yellow","green","blue","pink"],name='Colours')
z=pd.Series(["one","two","three","four","five"],name='Numbers')
df=pd.concat([x,y,z],axis=1)
df

Fruits Colours Numbers
0   apple     red     one
1  banana  yellow     two
2   mango   green   three
3    kiwi    blue    four
4  orange    pink    five

In [18]:
# B] Write a Python program to create a tuple of names and sort them in alphabetical order. 
names = ["Bob","Charlie","Ali","Dev","Eve","Buddy"]
sorted_names = tuple(sorted(names))
print("Sorted names:", sorted_names)

Sorted names: ('Ali', 'Bob', 'Buddy', 'Charlie', 'Dev', 'Eve')


In [22]:
# C]Write a program to create a dictionary from two lists using zip, where the first list contains keys and the second list contains values
keys = ['a','b','c','a','c']
values = [1,2,3,4,5]
combined_dict = {}
for key, value in zip(keys, values):
    if key in combined_dict:
        combined_dict[key].append(value)
    else:
        combined_dict[key]=[value]
combined_dict={key: value[0] if len(value)==1 else value for key, value in combined_dict.items()}
print(combined_dict)
        

{'a': [1, 4], 'b': 2, 'c': [3, 5]}


In [28]:
# 8] STATISTICAL ANALYSIS IN PANDAS
import pandas as pd
import numpy as np
a=pd.Series([1,2,3,4,5,6,7,8,9])
min=np.min(a)
max=np.max(a)
median=np.median(a)
percentile_25=np.percentile(a, 25)
percentile_75=np.percentile(a, 75)
print("minimum:",min)
print("maximum:",max)
print("Medain:", median)
print("percentile_25:",percentile_25)
print("percentile_75:",percentile_75)

minimum: 1
maximum: 9
Medain: 5.0
percentile_25: 3.0
percentile_75: 7.0


In [29]:
data=pd.Series(["apple","banana","apple","mango","banana","orange","kiwi","apple","kiwi"])
freq_counts=data.value_counts()
print("Frequency counts by unique items:")
print(freq_counts)
                

Frequency counts by unique items:
apple     3
banana    2
kiwi      2
mango     1
orange    1
Name: count, dtype: int64


In [31]:
import pandas as pd
import numpy as np
age=pd.Series(np.random.randint(100,size=10), name='age')
bin=[0,18,25,35,55,75,100]
lab=["teen","young","adult","mid-adult","old","senior-citizen"]
b=pd.cut(age, bins=bin, labels=lab)
df=pd.concat([age, b], axis=1)
df.columns=['age','age-group']
df

age       age-group
0   36       mid-adult
1   56             old
2   59             old
3   78  senior-citizen
4   13            teen
5   81  senior-citizen
6   25           young
7   11            teen
8   38       mid-adult
9   11            teen

In [32]:
a=np.array([1,2,3,4,5,6])
b=np.array([6,5,7,8,9,3])
c=np.linalg.norm(a-b)
c

9.539392014169456

In [33]:
# C]Write a set comprehension that generates a set of the first 10 prime numbers. 
primes = {x for x in range(2, 30) if all(x % y != 0 for y in range(2, int(x**0.5) + 1))}
print(primes)

{2, 3, 5, 7, 11, 13, 17, 19, 23, 29}


In [39]:
# 9} DATA PREPARATION IN PANDAS
import pandas as pd
a=pd.DataFrame({'col1':[10,20,30],'col2':[40,50,60]})
df=(a-a.min())/(a.max()-a.min())
df

col1  col2
0   0.0   0.0
1   0.5   0.5
2   1.0   1.0

In [44]:
data = pd.DataFrame({'A':[1,2,3,4,5],
                     'B':[2,4,6,8,10],
                     'C':[3,6,9,12,15]
                    })
correlation_with_next_row = df.corrwith(df.shift(-1))
print(correlation_with_next_row)

col1    1.0
col2    1.0
dtype: float64


In [46]:
import pandas as pd
import numpy as np
num_series = pd.Series(np.random.randint(1,100,100))
auto_correlation=num_series.autocorr()
print("auto corelation with lag 1:")
print(auto_correlation)

auto corelation with lag 1:
0.20252577850723869


In [47]:
# B]Create a NumPy array with the same shape and data type as an existing array, but leave its values uninitialized
import numpy as np
existing_array = np.array([1, 2, 3, 4, 5])
new_array = np.empty_like(existing_array)
print(new_array)

[0 1 2 3 4]


In [79]:
# B] How do you access the second element of a 2D NumPy array? 
import numpy as np
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:")
print(array)
print(array[0, 1])

Original array:
[[1 2 3]
 [4 5 6]]
2


In [51]:
#10]A) Multiple arrays 
#Stack two arrays vertically 
#Stack two arrays horizontally 
#Get the common items between two python numpy arrays 
#Remove from one array those items that exist in another 
#Get the positions where elements of two arrays match 
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
c=np.vstack((a,b))
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [52]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
c=np.hstack((a,b))
c

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [55]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[10,11,12]])
c=np.intersect1d(a,b)
c

array([1, 2, 3])

In [58]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3],[10,11,12]])
c=np.setdiff1d(a,b)
c

array([4, 5, 6])

In [59]:
a=np.array([[1,2,3,4,5,6]])
b=np.array([[1,2,3,10,11,12]])
c=np.where(a==b)
c

(array([0, 0, 0], dtype=int64), array([0, 1, 2], dtype=int64))

In [62]:
# B] Data Transformation 
#Normalize an array so the values range exactly between 0 and 1 
#Compute the min-by-max for each row for a numpy array 2d
import numpy as np
a=np.array([1.0,2.0,3.0,4.0,5.0])
arr_normalized=(a-np.min(a))/(np.max(a)-np.min(a))
print("normalized array (between 0 and 1)")
print(arr_normalized)


normalized array (between 0 and 1)
[0.   0.25 0.5  0.75 1.  ]


In [67]:
a=np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])
min_by_max=np.min(a, axis=1)/np.max(a, axis=1)
print("2D array")
print(a)
print("Normalized array:")
print(min_by_max)

2D array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized array:
[0.33333333 0.66666667 0.77777778]


In [74]:
#C)Write a program that takes two integer inputs from the user and prints 
#their product. If either input is not an integer, raise a TypeError exception and print an appropriate error message.
def main():
    try:
        num1 = int(input("Enter the first integer: "))
        num2 = int(input("Enter the second integer: "))
        product = num1 * num2
        print("The product is:", product)
    except ValueError:
        print("Error: Invalid input. Please enter an integer.")
if __name__ == "__main__":
    main()

Enter the first integer:  8
Enter the second integer:  0


The product is: 0
