In [ ]:
*********** Some binary universal functions **************

In [4]:
import numpy as np
rng = np.random.default_rng(seed=12345)
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.add(arr,2)
#add Add corresponding elements in arrays

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
np.subtract(arr,1)
#subtract Subtract elements in second array from first array

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [10]:
np.multiply(arr, 3)
#multiply Multiply array elements


array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [48]:
import numpy as np
rng = np.random.default_rng(seed=12345)
a=np.arange(5)
b=np.arange(6,11)
print("a",a)
print("b",b)
c=np.add(a, b)
d=np.subtract(a, b)
m=np.multiply(a, b)
p=np.divide(a, b)
f=np.floor_divide(a, b)
q=np.power(a, b)
max=np.maximum(a, b)
min=np.minimum(a, b)
mod=np.mod(a, b)
sign=np.copysign(a, b)
gre=np.greater(b, a)
gre1=np.greater_equal(a,b)
equal=np.not_equal(a, b)
log_add=np.logical_and(a, b)
log_or=np.logical_or(a, b)
log_xor=np.logical_xor(a, b)
print(c)
print(d)
print(m)
print(p)
print(q)
print(max)
print(min)
print(mod)
print(sign)
print(gre)
print(gre1)
print(equal)
print(log_add)
print(log_or)
print(log_xor)

a [0 1 2 3 4]
b [ 6  7  8  9 10]
[ 6  8 10 12 14]
[-6 -6 -6 -6 -6]
[ 0  7 16 27 40]
[0.         0.14285714 0.25       0.33333333 0.4       ]
[      0       1     256   19683 1048576]
[ 6  7  8  9 10]
[0 1 2 3 4]
[0 1 2 3 4]
[0. 1. 2. 3. 4.]
[ True  True  True  True  True]
[False False False False False]
[ True  True  True  True  True]
[False  True  True  True  True]
[ True  True  True  True  True]
[ True False False False False]
