In [5]:
# Universal Functions: Fast Element-Wise Array Fuctions

In [ ]:
import numpy as np
rng = np.random.default_rng(seed=12345)
x=rng.standard_normal(8)
y=rng.standard_normal(8)

In [6]:
x

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331,
       -0.74088465, -1.3677927 ,  0.6488928 ])

In [7]:
y

array([ 0.36105811, -1.95286306,  2.34740965,  0.96849691, -0.75938718,
        0.90219827, -0.46695317, -0.06068952])

In [9]:
np.minimum(x, y)

array([-1.42382504, -1.95286306, -0.87066174, -0.25917323, -0.75938718,
       -0.74088465, -1.3677927 , -0.06068952])

In [10]:
np.maximum(x, y)

array([ 0.36105811,  1.26372846,  2.34740965,  0.96849691, -0.07534331,
        0.90219827, -0.46695317,  0.6488928 ])

In [16]:
arr = rng.standard_normal(7) * 5
arr

array([ 3.88680672,  4.14316598, -4.79494157, -6.04694143, -7.06146007,
        2.70773415,  3.75969698])

In [17]:
remainder, whole_part = np.modf(arr)
#A vectorized version of the built-in Python math.modf, it returns the fractional and integral parts of a floating-point array:

In [18]:
remainder

array([ 0.88680672,  0.14316598, -0.79494157, -0.04694143, -0.06146007,
        0.70773415,  0.75969698])

In [19]:
whole_part

array([ 3.,  4., -4., -6., -7.,  2.,  3.])

In [20]:
arr

array([ 3.88680672,  4.14316598, -4.79494157, -6.04694143, -7.06146007,
        2.70773415,  3.75969698])

In [21]:
out = np.zeros_like(arr)

In [22]:
out

array([0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.add(arr, 1)

array([ 4.88680672,  5.14316598, -3.79494157, -5.04694143, -6.06146007,
        3.70773415,  4.75969698])